### ISSUE TITLE
TODO for release

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/art-salad#1]
- [x] Record a video playing a puzzle for comm.
- [x] Record a screenshot for site thumbnail and readme.
- [x] Rework the UI and particularly the homepage, write Art Salad.
- [x] Refactor the file system, put stuff in subfolders.
- [x] Setup GH Pages
- [x] Setup domain name with GH Pages
- [x] Add 2D Github button
- [x] Remove the license

**Comment by felixmariotto** [comment]
To add to the readme after GH pages is up:

> Want to give it a try ? Very simple:
> 1) Put on a virtual reality headset (Meta Quest is supported).
> 2) Launch the web browser.
> 3) Go to https://artsalad.net.
> 4) Click on `enter VR`.
> 5) Enjoy
