### ISSUE TITLE
Roadmap before application to Oculus Browser homepage

### ISSUE THREAD

**Issue by felixmariotto** [felixmariotto/art-salad#9]
Requirements [here](https://developer.oculus.com/documentation/web/browser-new-tab/).

- [x] Make title image of 2560 x 1440 pixels
- [x] Controller vibration #6 
- [x] Fix parts-controllers bugs #5 #4 
- [x] Pivot pieces toward camera #3
- [x] Feedback sounds #2

**Comment by felixmariotto** [comment]
https://630e031c55ae8d51dd93ff63--adorable-crepe-1f6fa8.netlify.app
